// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function make(dj, songs, param) {
  if (songs !== undefined) {
    return {
            dj: dj,
            songs: songs
          };
  } else {
    return {
            dj: dj,
            songs: /* [] */0
          };
  }
}

export {
  make ,
  
}
/* No side effect */
