// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SpotifyAPI$Turntableam from "../../server/services/SpotifyAPI.bs.js";

function handleSignInPKCE(param) {
  SpotifyAPI$Turntableam.AuthorizationPKCE.signIn(undefined);
  
}

function handleSignInImplicitGrant(param) {
  SpotifyAPI$Turntableam.AuthorizationImplicitGrant.signIn(undefined);
  
}

function Login(Props) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "Sign in to your Spotify Account"), React.createElement("button", {
                  onClick: (function (param) {
                      return handleSignInPKCE(undefined);
                    })
                }, "Sign In PKCE"), React.createElement("button", {
                  onClick: (function (param) {
                      return handleSignInImplicitGrant(undefined);
                    })
                }, "Sign In Implicit Grant"));
}

var make = Login;

export {
  handleSignInPKCE ,
  handleSignInImplicitGrant ,
  make ,
  
}
/* react Not a pure module */
