// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";

function getRequest(url, accessToken, onSuccess, onFail) {
  return fetch(url, {
                    headers: {
                      Authorization: "Bearer " + accessToken
                    }
                  }).then(function (response) {
                  return response.json();
                }).then(Curry.__1(onSuccess)).catch(Curry.__1(onFail));
}

function postRequest(url, body, accessToken, onSuccess, onFail) {
  return fetch(url, {
                    headers: {
                      Authorization: "Bearer " + accessToken
                    }
                  }).then(function (response) {
                  return response.json();
                }).then(Curry.__1(onSuccess)).catch(Curry.__1(onFail));
}

export {
  getRequest ,
  postRequest ,
  
}
/* No side effect */
