// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Uuid from "uuid";
import * as ReCrypt from "@space-labs/re-crypt/src/ReCrypt.bs.js";

var corsAnywhereUrl = "https://cors-anywhere.herokuapp.com/";

var authorizationBaseURI = "https://accounts.spotify.com/authorize";

var clientId = "96e25e1a56b5467fbbf82af545444904";

var localhostEncoded = "https%3A%2F%2Flocalhost%3A1234";

var scopes = [
  "playlist-modify-public",
  "playlist-modify-private",
  "playlist-read-private",
  "playlist-read-collaborative",
  "user-read-recently-played",
  "user-top-read",
  "ugc-image-upload",
  "user-follow-read",
  "user-library-read",
  "user-library-modify",
  "user-read-email",
  "user-read-private"
];

function urlEncode(arr) {
  return arr.join("%2C");
}

function generateCodeVerifier(param) {
  return Uuid.v4() + Uuid.v4();
}

function generateCodeChallenge(param) {
  return btoa(ReCrypt.Sha256.make(generateCodeVerifier(undefined)));
}

var scopesEncoded = scopes.join("%2C");

var state = Uuid.v4();

var codeChallenge = generateCodeChallenge(undefined);

var authorizationURI = "" + corsAnywhereUrl + authorizationBaseURI + "?response_type=code&client_id=" + clientId + "&redirect_uri=" + localhostEncoded + "&scope=" + scopesEncoded + "&state=" + state + "&code_challenge=" + codeChallenge + "&code_challenge_method=S256";

function signIn(param) {
  return fetch(authorizationURI).then(function (res) {
              return Promise.resolve((console.log(res), undefined));
            });
}

var Authorization = {
  corsAnywhereUrl: corsAnywhereUrl,
  authorizationBaseURI: authorizationBaseURI,
  clientId: clientId,
  localhostEncoded: localhostEncoded,
  scopes: scopes,
  urlEncode: urlEncode,
  generateCodeVerifier: generateCodeVerifier,
  generateCodeChallenge: generateCodeChallenge,
  scopesEncoded: scopesEncoded,
  state: state,
  codeChallenge: codeChallenge,
  authorizationURI: authorizationURI,
  signIn: signIn
};

var base = "https://api.spotify.com";

export {
  base ,
  Authorization ,
  
}
/* scopesEncoded Not a pure module */
