// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Uuid from "uuid";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as CamlinternalOO from "bs-platform/lib/es6/camlinternalOO.js";
import * as Ajax$Turntableam from "./Ajax.bs.js";

var authorizationBaseURI = "https://accounts.spotify.com/authorize";

var clientId = "96e25e1a56b5467fbbf82af545444904";

var localhostUnencoded = "http://localhost:1234";

var scopes = [
  "playlist-modify-public",
  "playlist-modify-private",
  "playlist-read-private",
  "playlist-read-collaborative",
  "user-read-recently-played",
  "user-top-read",
  "ugc-image-upload",
  "user-follow-read",
  "user-library-read",
  "user-library-modify",
  "user-read-email",
  "user-read-private",
  "streaming"
];

function urlEncode(arr) {
  return arr.join("%2C");
}

var state = Uuid.v4();

var scopesEncoded = scopes.join("%2C");

var finalEncodedUri = "" + authorizationBaseURI + "?client_id=" + clientId + "&response_type=token&redirect_uri=" + localhostUnencoded + "&state=" + state + "&scope=" + scopesEncoded;

var Authorization = {
  authorizationBaseURI: authorizationBaseURI,
  clientId: clientId,
  localhostUnencoded: localhostUnencoded,
  scopes: scopes,
  urlEncode: urlEncode,
  state: state,
  scopesEncoded: scopesEncoded,
  finalEncodedUri: finalEncodedUri
};

function searchArtist(accessToken, artist, onSuccess, onFail) {
  return Ajax$Turntableam.getRequest("https://api.spotify.com/v1/search?q=" + artist + "&type=artist", accessToken, onSuccess, onFail);
}

function searchTrack(accessToken, track, onSuccess, onFail) {
  return Ajax$Turntableam.getRequest("https://api.spotify.com/v1/search?q=" + track + "&type=track", accessToken, onSuccess, onFail);
}

var Search = {
  searchArtist: searchArtist,
  searchTrack: searchTrack
};

function getCurrentUsersProfile(accessToken) {
  return Ajax$Turntableam.getRequest("https://api.spotify.com/v1/me", accessToken, (function (p) {
                return p;
              }), (function (err) {
                console.log(err);
                return Promise.resolve(err);
              }));
}

var Profile = {
  getCurrentUsersProfile: getCurrentUsersProfile
};

var class_tables = /* Cons */{
  key: undefined,
  data: undefined,
  next: undefined
};

function create(param) {
  if (!class_tables.key) {
    var $$class = CamlinternalOO.create_table(0);
    var env = CamlinternalOO.new_variable($$class, "");
    var env_init = function (env$1) {
      var self = CamlinternalOO.create_object_opt(undefined, $$class);
      self[env] = env$1;
      return self;
    };
    CamlinternalOO.init_class($$class);
    class_tables.key = env_init;
  }
  return Curry._1(class_tables.key, undefined);
}

var Playlist = {
  create: create
};

var base = "https://api.spotify.com";

export {
  base ,
  Authorization ,
  Search ,
  Profile ,
  Playlist ,
  
}
/* state Not a pure module */
