// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var Page = {};

function make(param) {
  var match = React.useState(function () {
        return /* Home */0;
      });
  return {
          page: match[0],
          setPage: match[1]
        };
}

export {
  Page ,
  make ,
  
}
/* react Not a pure module */
