// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";

function changeTheme(theme, user) {
  return {
          id: user.id,
          username: user.username,
          friends: user.friends,
          avatarUrl: user.avatarUrl,
          preferredTheme: theme
        };
}

function addFriend(friend, user) {
  return {
          id: user.id,
          username: user.username,
          friends: {
            hd: friend,
            tl: user.friends
          },
          avatarUrl: user.avatarUrl,
          preferredTheme: user.preferredTheme
        };
}

function removeFriend(friend, user) {
  return {
          id: user.id,
          username: user.username,
          friends: List.filter(function (f) {
                  return f.id !== friend.id;
                })(user.friends),
          avatarUrl: user.avatarUrl,
          preferredTheme: user.preferredTheme
        };
}

export {
  changeTheme ,
  addFriend ,
  removeFriend ,
  
}
/* No side effect */
