// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Home from "./Home.bs.js";
import * as React from "react";
import * as UserProfile from "./UserProfile.bs.js";

function ApplicationContainer(Props) {
  var page = Props.page;
  var setPage = Props.setPage;
  if (page) {
    return React.createElement(UserProfile.make, {
                setPage: setPage
              });
  } else {
    return React.createElement(Home.make, {
                setPage: setPage
              });
  }
}

var make = ApplicationContainer;

export {
  make ,
  
}
/* Home Not a pure module */
