// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Home$Turntableam from "./Home.bs.js";
import * as UserProfile$Turntableam from "./UserProfile.bs.js";

function ApplicationContainer(Props) {
  var page = Props.page;
  var setPage = Props.setPage;
  if (page) {
    return React.createElement(UserProfile$Turntableam.make, {
                setPage: setPage
              });
  } else {
    return React.createElement(Home$Turntableam.make, {
                setPage: setPage
              });
  }
}

var make = ApplicationContainer;

export {
  make ,
  
}
/* react Not a pure module */
