// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$Error(Props) {
  var message = Props.message;
  return React.createElement("div", undefined, message);
}

var make = $$Error;

export {
  make ,
  
}
/* react Not a pure module */
