// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Footer(Props) {
  return React.createElement("footer", undefined, React.createElement("p", undefined, "Copyright 2020 by Moses A. Samuel"));
}

var make = Footer;

export {
  make ,
  
}
/* react Not a pure module */
