// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function Header(Props) {
  var setPage = Props.setPage;
  return React.createElement("header", undefined, React.createElement("ul", undefined, React.createElement("li", {
                      onClick: (function (param) {
                          return Curry._1(setPage, (function (param) {
                                        return /* Home */0;
                                      }));
                        })
                    }, "Home"), React.createElement("li", {
                      onClick: (function (param) {
                          return Curry._1(setPage, (function (param) {
                                        return /* UserProfile */1;
                                      }));
                        })
                    }, "Profile")));
}

var make = Header;

export {
  make ,
  
}
/* react Not a pure module */
