// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link$Turntableam from "./Link.bs.js";

function Header(Props) {
  var setPage = Props.setPage;
  return React.createElement("header", undefined, React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement(Link$Turntableam.make, {
                          to_: /* Home */0,
                          setPage: setPage,
                          children: "Home"
                        })), React.createElement("li", undefined, React.createElement(Link$Turntableam.make, {
                          to_: /* UserProfile */1,
                          setPage: setPage,
                          children: "Profile"
                        }))));
}

var make = Header;

export {
  make ,
  
}
/* react Not a pure module */
