// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Welcome to Turntable.AM"));
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
