// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function JoinRoom(Props) {
  return React.createElement("div", undefined);
}

var make = JoinRoom;

export {
  make ,
  
}
/* react Not a pure module */
