// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SpotifyAPI$Turntableam from "../services/SpotifyAPI.bs.js

function Login(Props) {
  return React.createElement("div", undefined, React.createElement("button", undefined, React.createElement("a", {
                      href: SpotifyAPI$Turntableam.Authorization.finalEncodedUri
                    }, "Log in with Spotify")));
}

var make = Login;

export {
  make ,
  
}
/* react Not a pure module */
