// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SpotifyAPI$Turntableam from "../services/SpotifyAPI.bs.js";

function handleSignIn(param) {
  SpotifyAPI$Turntableam.Authorization.signIn(undefined);
  
}

function Login(Props) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "Sign in to your Spotify Account"), React.createElement("button", {
                  onClick: (function (param) {
                      return handleSignIn(undefined);
                    })
                }, "Sign In"));
}

var make = Login;

export {
  handleSignIn ,
  make ,
  
}
/* react Not a pure module */
