// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SpotifyAPI$Turntableam from "../services/SpotifyAPI.bs.js";

((require("../styles/login.css")));

function Login(Props) {
  return React.createElement("div", {
              className: "login-container"
            }, React.createElement("button", undefined, React.createElement("a", {
                      href: SpotifyAPI$Turntableam.Authorization.finalEncodedUri
                    }, "Log in with Spotify")));
}

var make = Login;

export {
  make ,
  
}
/*  Not a pure module */
