// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function MusicPlayer(Props) {
  var match = React.useState(function () {
        return {
                currentTrack: "",
                currentArtist: "",
                currentAlbum: ""
              };
      });
  var musicPlayer = match[0];
  return React.createElement("div", undefined, React.createElement("h2", undefined, "Now Playing:"), React.createElement("p", undefined, "Track: " + musicPlayer.currentTrack + " "), React.createElement("p", undefined, "Artist: " + musicPlayer.currentArtist), React.createElement("p", undefined, "Album: " + musicPlayer.currentAlbum));
}

var make = MusicPlayer;

export {
  make ,
  
}
/* react Not a pure module */
