// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import RadioButtonsGroupJs from "./RadioButtonsGroup.js";

var make = RadioButtonsGroupJs;

var RadioButtonsGroup = {
  make: make
};

function handleSubmit($$event) {
  console.log("Playlist created");
  
}

function renderPlaylistCreationForm(param) {
  return React.createElement("form", {
              onSubmit: handleSubmit
            }, React.createElement(make, {
                  radioGroupName: "visibility",
                  formLabel: "Visibility",
                  inputLabels: [
                    {
                      value: "public",
                      label: "Public"
                    },
                    {
                      value: "private",
                      label: "Private"
                    }
                  ],
                  defaultValue: "public",
                  ariaLabel: "Playlist visibility"
                }), React.createElement("button", {
                  role: "submit"
                }, "Create"));
}

function renderPlaylistEditForm(param) {
  return React.createElement("div", undefined);
}

var Helpers = {
  handleSubmit: handleSubmit,
  renderPlaylistCreationForm: renderPlaylistCreationForm,
  renderPlaylistEditForm: renderPlaylistEditForm
};

function PlaylistCreator(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setShouldShowPlaylistCreationForm = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setShouldShowPlaylistEditForm = match$1[1];
  return React.createElement("div", undefined, React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(setShouldShowPlaylistCreationForm, (function (prevState) {
                                        return !prevState;
                                      }));
                        })
                    }, "Create a Playlist")), React.createElement("div", undefined, React.createElement("p", undefined, "-- Or --")), React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(setShouldShowPlaylistEditForm, (function (prevState) {
                                        return !prevState;
                                      }));
                        })
                    }, "Edit a friend's playlist")), match[0] ? renderPlaylistCreationForm(undefined) : React.createElement("div", undefined), match$1[0] ? renderPlaylistEditForm(undefined) : React.createElement("div", undefined));
}

var make$1 = PlaylistCreator;

export {
  RadioButtonsGroup ,
  Helpers ,
  make$1 as make,
  
}
/* make Not a pure module */
