// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import RadioButtonsGroupJs from "./RadioButtonsGroup.js";
import * as RoomFinder$Turntableam from "./RoomFinder.bs.js";

var make = RadioButtonsGroupJs;

var RadioButtonsGroup = {
  make: make
};

function handleSubmit($$event) {
  console.log("Playlist created");
  
}

function renderPlaylistCreationForm(param) {
  return React.createElement("form", {
              onSubmit: handleSubmit
            }, React.createElement(make, {
                  radioGroupName: "visibility",
                  formLabel: "Visibility",
                  inputLabels: [
                    {
                      value: "public",
                      label: "Public"
                    },
                    {
                      value: "private",
                      label: "Private"
                    }
                  ],
                  defaultValue: "public",
                  ariaLabel: "Playlist visibility"
                }), React.createElement("button", {
                  role: "submit"
                }, "Create"));
}

function renderRoomFinder(param) {
  return React.createElement(RoomFinder$Turntableam.make, {});
}

var Helpers = {
  handleSubmit: handleSubmit,
  renderPlaylistCreationForm: renderPlaylistCreationForm,
  renderRoomFinder: renderRoomFinder
};

function PlaylistCreator(Props) {
  var match = React.useState(function () {
        return /* Create */0;
      });
  var setJoinOrCreateRoom = match[1];
  var tmp;
  switch (match[0]) {
    case /* Create */0 :
        tmp = renderPlaylistCreationForm(undefined);
        break;
    case /* Join */1 :
        tmp = renderRoomFinder(undefined);
        break;
    case /* HasntSpecified */2 :
        tmp = React.createElement("div", undefined);
        break;
    
  }
  return React.createElement("div", undefined, React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(setJoinOrCreateRoom, (function (param) {
                                        return /* Create */0;
                                      }));
                        })
                    }, "Create a Playlist")), React.createElement("div", undefined, React.createElement("p", undefined, "-- Or --")), React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(setJoinOrCreateRoom, (function (param) {
                                        return /* Join */1;
                                      }));
                        })
                    }, "Edit a friend's playlist")), tmp);
}

var make$1 = PlaylistCreator;

export {
  RadioButtonsGroup ,
  Helpers ,
  make$1 as make,
  
}
/* make Not a pure module */
