// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function handleSubmit($$event) {
  $$event.preventDefault();
  console.log("submitted");
  
}

function RoomFinder(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setValue = match[1];
  return React.createElement("form", {
              onClick: handleSubmit
            }, React.createElement("input", {
                  type: "text",
                  value: match[0],
                  onChange: (function ($$event) {
                      return Curry._1(setValue, $$event.target.value);
                    })
                }), React.createElement("button", {
                  role: "submit"
                }, "Enter"));
}

var make = RoomFinder;

export {
  handleSubmit ,
  make ,
  
}
/* react Not a pure module */
