// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      header: {
        marginTop: 40
      }
    });

function UserProfile(Props) {
  Props.setPage;
  return React.createElement(ReactNative.View, {
              style: styles.header,
              children: React.createElement(ReactNative.Text, {
                    children: "Profile"
                  })
            });
}

var make = UserProfile;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
