// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function UserProfile(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Profile"));
}

var make = UserProfile;

export {
  make ,
  
}
/* react Not a pure module */
