// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as UsePage from "./hooks/UsePage.bs.js";
import * as ReactNative from "react-native";
import * as ApplicationContainer from "./components/ApplicationContainer.bs.js";
import * as NewAppScreen from "react-native/Libraries/NewAppScreen";

var Header = {};

var ReloadInstructions = {};

var LearnMoreLinks = {};

var DebugInstructions = {};

var styles = ReactNative.StyleSheet.create({
      scrollView: {
        backgroundColor: NewAppScreen.Colors.lighter
      },
      engine: {
        position: "absolute",
        right: 0
      },
      body: {
        backgroundColor: NewAppScreen.Colors.white
      },
      sectionContainer: {
        marginTop: 32,
        paddingHorizontal: 24
      },
      sectionTitle: {
        color: NewAppScreen.Colors.black,
        fontSize: 24,
        fontWeight: "600"
      },
      sectionDescription: {
        color: NewAppScreen.Colors.dark,
        fontSize: 18,
        fontWeight: "400",
        marginTop: 8
      },
      highlight: {
        fontWeight: "700"
      },
      footer: {
        color: NewAppScreen.Colors.dark,
        fontSize: 12,
        fontWeight: "600",
        textAlign: "right",
        padding: 4,
        paddingRight: 12
      }
    });

function App$app(Props) {
  var match = UsePage.make(undefined);
  return React.createElement(ApplicationContainer.make, {
              page: match.page,
              setPage: match.setPage
            });
}

var app = App$app;

export {
  Header ,
  ReloadInstructions ,
  LearnMoreLinks ,
  DebugInstructions ,
  styles ,
  app ,
  
}
/* styles Not a pure module */
