// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as App$Turntableam from "./components/App.bs.js";

((require("./index.css")));

ReactDOMRe.renderToElementWithId(React.createElement(App$Turntableam.make, {}), "root");

export {
  
}
/*  Not a pure module */
